apiVersion: v2
name: kube-binpacking-exporter
description: Prometheus exporter for Kubernetes binpacking efficiency
type: application
kubeVersion: ">= 1.29.0-0"
# Version is set to 0.0.0 in the repository. The actual version is injected
# by the release workflow at publish time and is never committed back to main.
version: 0.0.0
appVersion: "0.0.0"
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg
keywords:
  - kubernetes
  - prometheus
  - monitoring
  - binpacking
  - metrics
maintainers:
  - name: sherifabdlnaby
    url: https://github.com/sherifabdlnaby
sources:
  - https://github.com/sherifabdlnaby/kube-binpacking-exporter
home: https://github.com/sherifabdlnaby/kube-binpacking-exporter
